=== rackerlabs/atom-hopper/hopper/src/main/resources/META-INF/schema/config/atom-hopper-config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified"
           targetNamespace="http://atomhopper.org/atom/hopper-config/v1.0"
           xmlns:hopcfg="http://atomhopper.org/atom/hopper-config/v1.0"
           xmlns:xhtml="http://www.w3.org/1999/xhtml"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="atom-hopper-config" type="hopcfg:Configuration" />

    <xs:complexType name="Configuration">
        <xs:sequence>
            <xs:element name="defaults" type="hopcfg:ConfigurationDefaults" minOccurs="0" maxOccurs="1" />
            <xs:element name="host" type="hopcfg:HostConfiguration" minOccurs="1" maxOccurs="1" />
            <xs:element name="workspace" type="hopcfg:WorkspaceConfiguration" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ConfigurationDefaults">
        <xs:annotation>
            <xs:documentation>
                <xhtml:p>
                    Defines certain defaults which will be merged down into
                    configuration elements that have comparable analogues.
                </xhtml:p>
            </xs:documentation>
        </xs:annotation>

        <xs:sequence>
            <xs:element name="author" type="hopcfg:Author" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HostConfiguration">
        <xs:annotation>
            <xs:documentation>
                <xhtml:p>
                </xhtml:p>
            </xs:documentation>
        </xs:annotation>

        <xs:attribute name="domain" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>
                    <xhtml:p>
                    </xhtml:p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="WorkspaceConfiguration">
        <xs:annotation>
            <xs:documentation>
                <xhtml:p>
                    Describe an ATOMpub Workspace. A workspace is a logical
                    collection of related feeds.
                </xhtml:p>
            </xs:documentation>
        </xs:annotation>

        <xs:sequence>
            <xs:element name="defaults" type="hopcfg:ConfigurationDefaults" minOccurs="0" maxOccurs="1" />
            <xs:element name="feed-source" type="hopcfg:AdapterDescriptor" minOccurs="0" maxOccurs="1" />
            <xs:element name="feed-publisher" type="hopcfg:AdapterDescriptor" minOccurs="0" maxOccurs="1" />

            <xs:element name="feed" type="hopcfg:FeedConfiguration" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>

        <xs:attribute name="title" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>
                    <xhtml:p>
                        This sets the title of the workspace when a response is
                        generated for a client request
                    </xhtml:p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>

        <xs:attribute name="resource" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>
                    <xhtml:p>
                    </xhtml:p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="FeedConfiguration">
        <xs:sequence>
            <xs:element name="feed-source" type="hopcfg:AdapterDescriptor" minOccurs="0" maxOccurs="1" />
            <xs:element name="feed-publisher" type="hopcfg:AdapterDescriptor" minOccurs="0" maxOccurs="1" />
            <xs:element name="author" type="hopcfg:Author" minOccurs="0" maxOccurs="1" />
        </xs:sequence>

        <xs:attribute name="title" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>
                    <xhtml:p></xhtml:p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>

        <xs:attribute name="resource" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>
                    <xhtml:p></xhtml:p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="AdapterDescriptor">
        <xs:attribute name="reference" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>
                    <xhtml:p></xhtml:p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>

        <xs:attribute name="class" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>
                    <xhtml:p></xhtml:p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="ArchivalConfiguration">
        <xs:annotation>
            <xs:documentation>
                <xhtml:p></xhtml:p>
            </xs:documentation>
        </xs:annotation>

        <xs:sequence>
            <xs:element name="feed-archive-source" type="hopcfg:AdapterDescriptor" minOccurs="0" maxOccurs="1" />
            <xs:element name="feed-archiver" type="hopcfg:AdapterDescriptor" minOccurs="0" maxOccurs="1" />
        </xs:sequence>

        <xs:attribute name="interval-spec" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>
                    <xhtml:p></xhtml:p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="Author">
        <xs:attribute name="name" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>
                    <xhtml:p></xhtml:p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== rackerlabs/atom-hopper/test-suite/src/test/resources/META-INF/atom-server.cfg.xml
<?xml version="1.0" encoding="UTF-8"?>

<atom-hopper-config xmlns="http://atomhopper.org/atom/hopper-config/v1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://atomhopper.org/atom/hopper-config/v1.0 ./../../config/atom-hopper-config.xsd">
    <defaults>
        <author name="Atom Hopper" />
    </defaults>

    <host domain="domain.com" />

    <!-- http://localhost:8080/namespace_a/ -->
    <workspace title="A Testing Namespace" resource="/namespace/">
        <!-- http://localhost:8080/namespace_a/feed_1 -->
        <feed title="feed_1" resource="/feed">
            <feed-source reference="adapter" />
            <feed-publisher reference="adapter" />
        </feed>
    </workspace>
    
    <workspace title="Another Testing Namespace" resource="/uber-namespace/">
        <feed title="uber-feed" resource="/uberfeed">
            <feed-source reference="adapter" />
            <feed-publisher reference="adapter" />
        </feed>
    </workspace>    
</atom-hopper-config>

=== rackerlabs/atom-hopper/hopper/src/main/resources/META-INF/schema/examples/config/feed-server-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<atom-hopper-config xmlns="http://atomhopper.org/atom/hopper-config/v1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://atomhopper.org/atom/hopper-config/v1.0 ./../../config/atom-hopper-config.xsd">
    <defaults>
        <author name="Atom Hopper" />
    </defaults>

    <host domain="domain.com" scheme="http" />

    <workspace title="Testing Namespce" resource="/test/">
        <defaults>
            <author name="Atom Hopper in Workspace" />
        </defaults>

        <categories-descriptor reference="workspace-categories-descriptor" />

        <feed title="Testing Feed" resource="/feed" archived="false">
            <feed-source reference="feed-source-adapter" />

            <publisher reference="net.jps.atom.adapter.InMemoryPublisher">
                <parameter name="net.jps.atom.adapter.db.show_sql" value="true" />
            </publisher>
        </feed>

        <feed title="Testing Feed Archive" resource="/archive/" archived="true">
            <feed-source reference="feed-archive-adapter" />
        </feed>
    </workspace>

    <workspace title="Testing Namespce Part Two" resource="/test_2/">
        <defaults>
            <author name="Atom Hopper in Workspace" />
        </defaults>

        <feed title="Testing Feed Archive Part Two" resource="/archive/feed" archived="true">
            <feed-source reference="feed-archive-adapter" />
        </feed>
    </workspace>
</atom-hopper-config>

=== rackerlabs/atom-hopper/hopper/src/test/resources/org/atomhopper/config/WorkspaceConfigProcessorTest/noArchiveWithArchive.xml
<?xml version="1.0" encoding="UTF-8"?>

<atom-hopper-config xmlns="http://atomhopper.org/atom/hopper-config/v1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://atomhopper.org/atom/hopper-config/v1.0 ./../../config/atom-hopper-config.xsd">
    <defaults>
        <author name="Atom Hopper" />
    </defaults>

    <host domain="domain.com" scheme="http" />

    <workspace title="Testing Namespce" resource="/test/">
        <defaults>
            <author name="Atom Hopper in Workspace" />
        </defaults>

        <categories-descriptor reference="workspace-categories-descriptor" />

        <feed title="Testing Feed Archive" resource="/archive/">
            <feed-source reference="feed-archive-adapter" />
        </feed>
    </workspace>

</atom-hopper-config>
